name: zyvi_tv
description: Zyvi TV - Cross-platform Live TV & VOD streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  better_player: ^0.0.84
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon_foreground.png
    - assets/images/main_logo.png
    - assets/images/splash_screen.png
    - assets/images/login_artwork.png
    - assets/images/tv_banner.png
    - assets/images/web_hero_banner.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#080C16"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  remove_alpha_ios: true
  min_sdk_android: 21
